name: mainDocs_Sync_To_Wiki
# Synchronisiert das Wiki mit ./docs (info:https://github.com/newrelic/wiki-sync-action/tree/main)

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GIT_AUTHOR_NAME: SpacerX
  GIT_AUTHOR_EMAIL: rbe@spacerx.de
 
jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.RBE_TOKEN }}
          ref: main
      
      # from main (requiere: Dockerfile, action.yml, entrypoint.sh)
      #- name: Sync docs to wiki 
      #  uses: SpacerX/Sync-DocsAndWiki-Actions@main         
       
      # from Marketplace (Bi-directional Wiki Sync Action)
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@v1.0.1   
        with:
          branch: main
          source: docs
          destination: wiki
          token: ${{ secrets.RBE_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
